version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Bundler install
          command: gem install bundler
      - run:
          name: Dependencies install
          command: bundle install
      - run:
          name: Execute tests
          command: ruby app/tests/tests.rb

